name: attendance_tracker
description: A Flutter app for tracking student attendance with enhanced subject management.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # UI & Animations
  flutter_animate: ^4.5.0
  fl_chart: ^0.66.0

  # Data Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1

  # Notifications
  flutter_local_notifications: ^17.2.0
  timezone: ^0.9.2

  # File Operations
  excel: ^4.0.6
  share_plus: ^7.2.1
  csv: ^5.0.2

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
